# -*- coding: utf-8 -*-
"""YOLO11_Updated.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hD-XJFMFHBJ8MlqTMh6OC266LZDWrw5u

Import ultralytics
"""

!pip install ultralytics

import ultralytics
from ultralytics import YOLO

ultralytics.checks()

"""  Download the Dataset from Roboflow"""

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="hzoVrDHDbdeFNRLoh2Nq")
project = rf.workspace("pose-detection-twxbg").project("human-activity-ce7zu")
version = project.version(2)
dataset = version.download("yolov8")

"""YOLO11 Model"""

model = YOLO("yolo11s-pose.pt")

"""Train the YOLO11 Pose Model"""

results = model.train(data = "/content/Human-activity-2/train", task = "pose", mode = "train", imgsz = 640, epochs = 100, batch = 8)

